language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - pytest
  - nosetests tests
  - coverage run test_hello.py

# Report results to DeepSource
after_success:
  # Generate coverage report in xml format
  - coverage xml

  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # Report coverage artifact to 'test-coverage' analyzer
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml

deploy:
provider: heroku
api_key: 48f07951-cda8-4d9b-b522-49f1ae16a985
app:
  production: covid-tracking-wgu